name: MinePass
version: '${version}'
main: io.github.duckycashy.minepass.MinePassPlugin
description: Password protection for Paper servers
author: DuckyCashy
website: https://github.com/DuckyCashy/MinePass
api-version: '1.21.11'

commands:
  mp:
    description: MinePass administration command
    usage: /mp <list|create|delete|lockserver|unlockserver|update>
    permission: minepass.admin

permissions:
  minepass.admin:
    description: Allows administration of MinePass
    default: op